version: '3'
services:
  web:
    container_name: srv-apache
    image: lfmc/iso-apache
    build: .
    volumes:
      - ./apache:/var/www/html
    ports:
      - "81:80"
    networks:
      - net
networks:
  net: