version: '3'
services:
  web:
    container_name: srv-apache
    image: jorarmarfin/apache-php:7.2
    volumes:
      - ./apache/html:/var/www/html
    ports:
      - ${PUERTO_APACHE}:80
    restart: always
    networks:
      - net-apache
  db:
    container_name: srv-mysql
    image: mysql:5.7
    ports:
      - ${PUERTO_MYSQL}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${PASS_MYSQL}
    volumes:
      - ${MYSQL_FILES}:/var/lib/mysql
      - ${MYSQL_CONFIG}:/etc/mysql/conf.d
    restart: always
    networks:
      - net-apache
  adminer:
    container_name: srv-adminer
    image: adminer:latest
    ports:
      - ${PUERTO_GESTOR}:8080
    restart: always
    networks:
      - net-apache
networks:
  net-apache: