version: '3'
services:
  web:
    container_name: srv-apache
    image: lfmc/iso-apache:${VERSION_PHP}
    build: .
    volumes:
      - ./apache/html:/var/www/html
    ports:
      - "81:80"
    networks:
      - net-apache
    restart: always
  db:
    container_name: srv-potgres
    image: postgres:10.4
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=${PASS_PGSQL}
    volumes:
      - ${PGSQL_FILES}:/var/lib/postgresql/data postgres
    restart: always
    networks:
      - net-apache
  admin:
    container_name: srv-adminer
    image: adminer:latest
    ports:
      - 8080:8080
    restart: always
    networks:
      - net-apache
networks:
  net-apache: