version: '3'
services:
  web:
    container_name: srv-laravel
    image: lfmc/iso-laravel
    build: .
    volumes:
      - /home/lmayta/Docker/Volumen/apache/html:/var/www/html
    ports:
      - "81:80"
    networks:
      - net
networks:
  net: