version: '3'

services:
  web:
    container_name: srv-apache-test
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
        - '9001:80'
    volumes:
        - './web:/var/www/html'